version: '3.8'

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      target: development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000